/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/assets/galaxy.glb 
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Galaxy(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/galaxy.glb");

  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Global Rotation"].play();
  });
  return (
    <group ref={group} {...props} dispose={null} scale={10} position-z={-10}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        >
          <group
            name="c0d234900f694cb2b1f4f457c9f91791fbx"
            rotation={[-Math.PI, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="StarCluster3" scale={100}>
                  <group name="Object_5" position={[-0.703, 0, 0]}>
                    <mesh
                      name="StarCluster3_03_-__0"
                      geometry={nodes["StarCluster3_03_-__0"].geometry}
                      material={materials["03_-"]}
                    />
                  </group>
                </group>
                <group name="StarCluster2" scale={49.606}>
                  <group name="Object_8" position={[-1.549, 0, 0]}>
                    <mesh
                      name="StarCluster2_02_-__0"
                      geometry={nodes["StarCluster2_02_-__0"].geometry}
                      material={materials["02_-"]}
                    />
                  </group>
                </group>
                <group name="StarCluster1" scale={24.803}>
                  <group name="Object_11" position={[-1.993, 0, 0]}>
                    <mesh
                      name="StarCluster1_01_-__0"
                      geometry={nodes["StarCluster1_01_-__0"].geometry}
                      material={materials["01_-"]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/galaxy.glb");
