/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/assets/steven.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useFBX, useAnimations } from "@react-three/drei";

export default function Steven(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("src/assets/steven.glb");

  const { animations: wavingAnimation } = useFBX("src/assets/Waving.fbx");

  wavingAnimation[0].name = "Waving";
  const { actions } = useAnimations(wavingAnimation, group);

  useEffect(() => {
    actions["Waving"].reset().play();
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={0.005}
      position={[0, 0, 1]}
      ref={group}
    >
      <group rotation={[0, 0, 0]}>
        <primitive object={nodes.Origin} />
        <skinnedMesh
          geometry={nodes.mesh_0_body.geometry}
          material={materials.rstr0012_00_fi_body}
          skeleton={nodes.mesh_0_body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.mesh_1_face.geometry}
          material={materials.rstr0012_00_fi_face}
          skeleton={nodes.mesh_1_face.skeleton}
        />
        <skinnedMesh
          geometry={nodes.mesh_2_hair.geometry}
          material={materials.rstr0012_00_fi_head}
          skeleton={nodes.mesh_2_hair.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("src/assets/steven.glb");
